### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by knownasilya** [vitch/ember-cli-webfont#1]
Hello!

Trying to get this to work, but nothing seems to appear in my app.

I have `app/webfont/svg/abutters.svg` which is:

``` svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"  width="24" height="24" viewBox="0 0 24 24">
   <path fill="#666" d="M3 1 M3 21 H11 V13 H3 M13 21 H21 V13 H13 M13 3 V11 H21 V3" />
</svg>
```

and I use it with `<span class="iconfont iconfont-abutters"></span>` but the element has no special styles and just appears blank.

**Comment by vitch** [comment]
I presume you got it to work? What was the problem? Let me know if I can update the docs to be clearer on anything...

**Comment by knownasilya** [comment]
The default folder is `/app/webfont-svg`, not `/app/webfont/svg` like the readme says.

**Comment by vitch** [comment]
Thanks!
