### ISSUE TITLE
Cannot use SCSS template

### ISSUE THREAD

**Issue by ncoden** [vitch/ember-cli-webfont#5]
Hello,

Because `broccoli-webfont` transforms paths (`files`, `dest`, `cssDest` and `htmlDest`) to make them relative to broccoli source/dist paths, the SCSS generated by `webfonts-generator` (or any other SCSS template) is directly compiled into .css (even if it is still SCSS).

So when using a SCSS template, no SCSS file can be imported into our application, and this code pollute the distributed CSS.

I think a solution would be to override this `broccoli-webfont` behavior or fork it (it is no longer maintained), to propose a new `templateType` option (with at least `CSS` and `SCSS`).

@vitch What do you think ?

**Comment by joankaradimov** [comment]
We had a hacky workaround for this which is described here: https://github.com/ember-cli/ember-cli/issues/8122

However, it stopped working in ember-cli 3.5.

I've created a pull request that fixes both. It just requires some configuration that should go into `ember-cli-build.js`. Namely - you need to explicitly state the `cssDest` file:

```
    webfont: {
      path: 'app/webfonts',
      options: {
        ...........
        cssDest: 'app/styles/iconfont.scss',
        cssTemplate: 'app/webfonts/_template.scss.hbs',
      }
    },
```

After that in `app.scss` you can simply do this:

```
@import './iconfont';
```
